package subway.outputview;

public enum OutputViewName {
    STATION_COMMAND, STATION_TO_SAVE, STATION_TO_DELETE, FIND_ALL_STATIONS, LINE_COMMAND, LINE_SAVE, LINE_SAVE_FIRST_STATION, LINE_SAVE_LAST_STATION, LINE_DELETE, LINE_DELETE_COMPLETE, FIND_ALL_LINES, SECTION_COMMAND, SECTION_SAVE_LINE, SECTION_SAVE_STATION, SECTION_SAVE_ORDER, MAIN
}
