package subway.outputview;

public enum OutputViewName {
    STATION_COMMAND, STATION_TO_SAVE, STATION_TO_DELETE, FIND_ALL_STATIONS, LINE_COMMAND, LINE_SAVE, LINE_SAVE_FIRST_STATION, LINE_SAVE_LAST_STATION, LINE_DELETE, LINE_DELETE_COMPLETE, MAIN
}
